# Generated by Django 4.2.4 on 2023-10-04 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cv_date', models.DateField(auto_now=True)),
                ('cv_education', models.TextField(max_length=500)),
                ('cv_career', models.TextField(max_length=700)),
                ('cv_skills', models.TextField(max_length=500)),
                ('cv_other', models.TextField(max_length=700, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_of_birth', models.DateField(default=None, help_text='YYYY-MM-DD', null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('creg_number', models.CharField(blank=True, max_length=8)),
                ('company_descript', models.TextField(blank=True, max_length=500)),
                ('is_seeker', models.BooleanField(default=False, help_text='Registering to seek employees? Tick this!')),
            ],
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=100)),
                ('job_desc', models.TextField(max_length=500)),
                ('job_field', models.CharField(max_length=100)),
                ('job_skills', models.TextField(max_length=500)),
                ('job_date', models.DateField(auto_now=True)),
                ('published', models.BooleanField(default=True, help_text='Untick to save as draft')),
                ('job_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
