# Generated by Django 4.2.4 on 2023-10-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposition',
            name='job_source',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
