# Generated by Django 4.2.4 on 2023-10-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_jobposition_job_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposition',
            name='job_about',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='job_email',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
