# Generated by Django 4.2.4 on 2023-10-04 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_jobposition_job_about_jobposition_job_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='cv_dob',
            field=models.DateField(default=None, help_text='YYYY-MM-DD', null=True),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='cv_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='cv_fname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='cv_lname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
